mysql:
    url: 127.0.0.1
    port: 3306
redis:
    host: localhost
    port: 6379
    info:
        username: alex
        password: "123456"
        permission:
            - 1
            - 3
            - 5
